### ISSUE TITLE
TODO

### ISSUE THREAD

**Issue by AntoineDupre** [AntoineDupre/2018-tango-meeting#1]
summary 

problematic (MIL): 
 • different input
 • diverse configuration under subsystem owner

The tool (AND)
 • Json format
 • print out 
 • dump

Usage 
 • MAGNET (MIL) 
 • PLC (AND)
    ◦ AUTOMATION
    ◦ NAME RESOLUTION
    ◦ ALARMS
    ◦ HLDEVICE
    - CABLE DB

 • SARDANA (MIL)
  • HDB++ (AND)

Futures ?

**Comment by mirlin** [comment]
More things to consider:
Background:
Number of subsystems and devices at MAX IV
Naming convention
Recurring changes and additions to the Tango configuration
